name: Lint and Format

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort black mypy

      - name: Run Flake8
        run: flake8 wallet

      - name: Run isort
        run: isort --check wallet

      - name: Run Black
        run: black --check wallet

      - name: Run mypy
        run: mypy --allow-untyped-decorators wallet
