name: Run Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  run-pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Pytest
        run: |
          test_files=$(find wallet/tests/ -type f -name 'test_*' | wc -l)
          if [ "$test_files" -eq 0 ]; then
            echo "No tests found. Exiting."
            exit 0
          else
            echo "Found test file(s). Running pytest..."
            pytest ./wallet/tests/
          fi
